---

/**:
  ros__parameters:
    path: Aggregation
    graph:
      type: diagnostic_aggregator/AnalyzerGroup
      path: RosGraph
      startswith: ["/rosgraph"]
      analyzers:
        nodes:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Nodes
          contains: ["/nodes"]
        continuity:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Continuity
          contains: ["/continuity"]
        frequency:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Frequency
          contains: ["/topic_frequency"]
