// SPDX-FileCopyrightText: 2025 Polymath Robotics, Inc.
// SPDX-License-Identifier: Apache-2.0

#include "gtest/gtest.h"
#include "rmw/types.h"
#include "rosgraph_msgs/msg/qo_s_profile.hpp"

/**
 * Tests to ensure that the rosgraph_msgs::msg::QoSProfile constants
 * stay in sync with the target ROS distribution.
 */
class QosProfileConstantsTest : public ::testing::Test
{};

TEST(QosProfileConstantsTest, HistoryPolicyConstantsMatchRclcpp)
{
  using QosMsg = rosgraph_msgs::msg::QoSProfile;

  EXPECT_EQ(QosMsg::HISTORY_SYSTEM_DEFAULT, RMW_QOS_POLICY_HISTORY_SYSTEM_DEFAULT);
  EXPECT_EQ(QosMsg::HISTORY_KEEP_LAST, RMW_QOS_POLICY_HISTORY_KEEP_LAST);
  EXPECT_EQ(QosMsg::HISTORY_KEEP_ALL, RMW_QOS_POLICY_HISTORY_KEEP_ALL);
  EXPECT_EQ(QosMsg::HISTORY_UNKNOWN, RMW_QOS_POLICY_HISTORY_UNKNOWN);
}

TEST(QosProfileConstantsTest, ReliabilityPolicyConstantsMatchRclcpp)
{
  using QosMsg = rosgraph_msgs::msg::QoSProfile;

  EXPECT_EQ(QosMsg::RELIABILITY_SYSTEM_DEFAULT, RMW_QOS_POLICY_RELIABILITY_SYSTEM_DEFAULT);
  EXPECT_EQ(QosMsg::RELIABILITY_RELIABLE, RMW_QOS_POLICY_RELIABILITY_RELIABLE);
  EXPECT_EQ(QosMsg::RELIABILITY_BEST_EFFORT, RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT);
  EXPECT_EQ(QosMsg::RELIABILITY_UNKNOWN, RMW_QOS_POLICY_RELIABILITY_UNKNOWN);
  EXPECT_EQ(QosMsg::RELIABILITY_BEST_AVAILABLE, RMW_QOS_POLICY_RELIABILITY_BEST_AVAILABLE);
}

TEST(QosProfileConstantsTest, DurabilityPolicyConstantsMatchRclcpp)
{
  using QosMsg = rosgraph_msgs::msg::QoSProfile;

  EXPECT_EQ(QosMsg::DURABILITY_SYSTEM_DEFAULT, RMW_QOS_POLICY_DURABILITY_SYSTEM_DEFAULT);
  EXPECT_EQ(QosMsg::DURABILITY_TRANSIENT_LOCAL, RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL);
  EXPECT_EQ(QosMsg::DURABILITY_VOLATILE, RMW_QOS_POLICY_DURABILITY_VOLATILE);
  EXPECT_EQ(QosMsg::DURABILITY_UNKNOWN, RMW_QOS_POLICY_DURABILITY_UNKNOWN);
  EXPECT_EQ(QosMsg::DURABILITY_BEST_AVAILABLE, RMW_QOS_POLICY_DURABILITY_BEST_AVAILABLE);
}

TEST(QosProfileConstantsTest, LivelinessPolicyConstantsMatchRclcpp)
{
  using QosMsg = rosgraph_msgs::msg::QoSProfile;

  EXPECT_EQ(QosMsg::LIVELINESS_SYSTEM_DEFAULT, RMW_QOS_POLICY_LIVELINESS_SYSTEM_DEFAULT);
  EXPECT_EQ(QosMsg::LIVELINESS_AUTOMATIC, RMW_QOS_POLICY_LIVELINESS_AUTOMATIC);
  EXPECT_EQ(QosMsg::LIVELINESS_MANUAL_BY_TOPIC, RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_TOPIC);
  EXPECT_EQ(QosMsg::LIVELINESS_UNKNOWN, RMW_QOS_POLICY_LIVELINESS_UNKNOWN);
  EXPECT_EQ(QosMsg::LIVELINESS_BEST_AVAILABLE, RMW_QOS_POLICY_LIVELINESS_BEST_AVAILABLE);
}
