---
name: Build and test
"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [rmw_stats_shim, rosgraph_monitor, rosgraph_monitor_msgs, rosgraph_monitor_test]
        ros: [humble, jazzy, kilted, rolling]
        include:
          - ros: humble
            ubuntu: jammy
          - ros: jazzy
            ubuntu: noble
          - ros: kilted
            ubuntu: noble-testing
          - ros: rolling
            ubuntu: noble
    name: ${{ matrix.package }} (${{ matrix.ros }})
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-${{ matrix.ubuntu }}:latest
    env:
      ROS_DISTRO: ${{ matrix.ros }}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      RMW_IMPLEMENTATION_WRAPPER: rmw_stats_shim
    steps:
      - uses: actions/checkout@v4
      - name: Create dependency repos file
        shell: bash
        run: |
          cat << 'EOF' > /tmp/deps.repos
          {"repositories":
            {"rmw_implementation":
              {"type": "git",
              "url": "https://github.com/robograph-project/rmw_implementation",
              "version": "${{ matrix.ros }}-rmw-wrapper"
              }
            }
          }
          EOF
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros }}
          vcs-repo-file-url: /tmp/deps.repos
          package-name: ${{ matrix.package }}
          rosdep-skip-keys: rmw_connextdds
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_CXX_FLAGS=\"-Werror\""
                ]
              }
            }
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs__${{ matrix.package }}__${{ matrix.ros }}
          path: ros_ws/log
